### ISSUE TITLE
Static analysis with coverage

### ISSUE THREAD

**Issue by 4everTheOne** [MockBukkit/MockBukkit#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Today we don't have information regarding coverage in SonarCloud.

**Comment by 4everTheOne** [comment]
Findings at the moment:
> I need you help regarding PR https://github.com/MockBukkit/MockBukkit/pull/1104. I've been trying to integrate the coverage report with SonarCloud, for us to have that information in the dashboard, but after some research regarding this topic, i found out that SonarCloud has two types of scans, Automatic Analysis and CI Analysis.
> 
> At the moment we have been using Automatic Analysis to fill the information in the dashboard, but this has some limitations where on of them is "Code coverage information is not supported." (Source: https://docs.sonarsource.com/sonarcloud/advanced-setup/automatic-analysis/#prerequisites ).
> 
> In order to have coverage in our SonarCloud dashboard we need to migrate to CI Analysis, which was done in the PR mentioned above, but was not enough. For this development to be completed we need to deactivate Automatic Analysis in the Administration Dashboard (Ref: https://docs.sonarsource.com/sonarcloud/advanced-setup/automatic-analysis/#deactivating-automatic-analysis), due to conflicts between Automatic Analysis and CI Analysis (https://docs.sonarsource.com/sonarcloud/advanced-setup/automatic-analysis/#conflict-with-ci-based-analysis).

**Comment by Thorinwasher** [comment]
@4everTheOne 

Is this fixed now / can we close this issue?

**Comment by 4everTheOne** [comment]
Hello @Thorinwasher. It's not resolved yet:
![image](https://github.com/user-attachments/assets/c8199a59-4c16-4991-8d7d-afb7a32a5c12)
