### ISSUE TITLE
Failure to sign publications

### ISSUE THREAD

**Issue by TheBusyBiscuit** [MockBukkit/MockBukkit#90]
## Description
I am unable to build projects against the latest versions of MockBukkit due to errors in the "publication signing" process.
I don't think I have sufficient enough experience with gradle and PGP so I will just raise an issue for this here instead.

I was building against the latest commit:
**MockBukkit:v1.15** - 304baf8af81cae1eb4aeaf232a70b3145719b103

## Log
`> Cannot perform signing task ':signMockBukkitPublication' because it has no configured signatory`
Here is the full build log:
https://jitpack.io/com/github/seeseemelk/MockBukkit/v1.15-304baf8af8-1/build.log

I am not quite sure what exactly is going wrong here but I hope that someone will be able to find out.

**Comment by seeseemelk** [comment]
Hm, normally it should now be published automatically to Maven central, so JitPack shouldn't be necessary anymore. However, I've noticed that even that Travis is failing to deploy it. I will look more into this.

**Comment by seeseemelk** [comment]
#91 should fix this.

**Comment by seeseemelk** [comment]
Deployment succeeded. See if you can use the latest `SNAPSHOT`-version from Maven Central instead of the version from Jitpack.

**Comment by TheBusyBiscuit** [comment]
Awesome, thank you!

Not really sure what the latest version would be here, always built against the commit of MockBukkit until now. 
But the SNAPSHOT of 0.3.1 definitely seems to still be an older build.

```xml
<dependency>
  <groupId>com.github.seeseemelk</groupId>
  <artifactId>MockBukkit-v1.15</artifactId>
  <version>0.3.1-SNAPSHOT</version>
  <scope>test</scope>
</dependency>
```

**Comment by seeseemelk** [comment]
I was accidentally publishing under the wrong name. That should be fixed now.

**Comment by TheBusyBiscuit** [comment]
Hmm, still no luck with that. `0.3.1-SNAPSHOT` is the correct version to use, right?

**Comment by seeseemelk** [comment]
`0.3.1-SNAPSHOT` should be the correct version. According to [sonatype](https://oss.sonatype.org), the current latest version was published `Thu Aug 06 2020 23:05:16 GMT+0200`, which should be the correct version. Are you sure Maven isn't using a locally cached version?

**Comment by TheBusyBiscuit** [comment]
> Are you sure Maven isn't using a locally cached version?
Absolutely, clearing my .m2 folder is the very first thing I do in cases like this, I have cleared the cache yesterday prior to testing it, while also performing a force-update on all snapshots.

I just tested it again and it seems to still persist.
And on sonatype, the version 0.3.1-SNAPSHOT does not seem to even show up for me.
![5568c6781daa9a22a16d7f7d19229382](https://user-images.githubusercontent.com/3967898/89659547-517a7b00-d8d0-11ea-8ed5-73236330a8dc.png)

Strangely enough, Maven is able to find 0.3.1-SNAPSHOT but it is a much older version.
So I dug into the cache and found out that Maven fails to find version 0.3.1-SNAPSHOT on Maven Central, but it does find it in another repository: PaperMC.

And strangely enough, there it is:
https://papermc.io/repo/#browse/browse:maven-public:com%2Fgithub%2Fseeseemelk%2FMockBukkit-v1.15%2F0.3.1-SNAPSHOT

So for some reason Maven cannot find it on central but there appears to be a version of MockBukkit on PaperMC which my project wants to build against.
Quite peculiar.

**Comment by seeseemelk** [comment]
How did a version of MockBukkit end up on PaperMC? And it seems that the version on PaperMC is a pretty new version. I wonder if maybe it takes a while for snapshot versions to be published on sonatype. I'll have to dig deeper into that.

**Comment by seeseemelk** [comment]
It seems that with Maven one has to manually specify the Sonatype Snapshot repository. ([https://stackoverflow.com/a/56145228/1520634](https://stackoverflow.com/a/56145228/1520634))

Does adding the following repository to your `pom.xml` fix the issue?
```xml
<repository>
    <id>oss.sonatype.org-snapshot</id>
    <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```

EDIT:
I do see the package on Sonatype, even when not logged in.
![Screenshot_2020-08-07_17-24-17](https://user-images.githubusercontent.com/2057687/89661409-f39b6280-d8d2-11ea-8e95-08f728b572f6.png)

**Comment by TheBusyBiscuit** [comment]
Adding the sonatype repository manually has definitely fixed it :)
We should probably update the README at some point to include that, thanks for looking into this though!

Still not really sure why it doesn't show up on sonatype for me (Yep, it still doesn't).
But oh well, at least I can now build projects against the latest version.

Btw GitHub also provides a package repository now which is pretty easy to use from what I have seen, haven't really looked into it too deeply though. Just pointing this out here in case any other strangeness occurs in the future!
Anyway, thanks again, I am closing this Issue as resolved now!
